const CORE_DATA_URL = "./data/cards.json";
const CARD_DATA_INDEX_URL = "./data/cards/index.json";

const FALLBACK_CARD_DATA_FILES = [];

const RARITY_META = {
  common: { name: "Common", icon: "🟢", order: 10 },
  common_plus: { name: "Common+", icon: "🟢", order: 11 },
  uncommon: { name: "Uncommon", icon: "⚫", order: 20 },
  uncommon_plus: { name: "Uncommon+", icon: "◼️", order: 21 },
  rare: { name: "Rare", icon: "🔵", order: 30 },
  rare_plus: { name: "Rare+", icon: "🟦", order: 31 },
  epic: { name: "Epic", icon: "🟣", order: 40 },
  epic_plus: { name: "Epic+", icon: "🟪", order: 41 },
  epic_event: { name: "Epic [EVENT]", icon: "🟣", order: 42 },
  epic_limited: { name: "Epic [LIMITED]", icon: "🟣", order: 43 },
  legendary: { name: "Legendary", icon: "🟠", order: 50 },
  legendary_plus: { name: "Legendary+", icon: "🟧", order: 51 },
  legendary_bundle: { name: "Legendary [BUNDLE]", icon: "🟠", order: 52 },
  legendary_event: { name: "Legendary [EVENT]", icon: "🟠", order: 53 },
  legendary_limited: { name: "Legendary [LIMITED]", icon: "🟠", order: 54 },
  legendary_pack: { name: "Legendary [PACK]", icon: "🟠", order: 55 },
  relic: { name: "Relic", icon: "🟡", order: 60 },
  relic_plus: { name: "Relic+", icon: "🟨", order: 61 },
  relic_event: { name: "Relic [EVENT]", icon: "🟡", order: 62 },
  relic_limited: { name: "Relic [LIMITED]", icon: "🟡", order: 63 },
  mythical: { name: "Mythical", icon: "⚪", order: 70 },
  mythical_plus: { name: "Mythical+", icon: "◻️", order: 71 },
  mythical_event: { name: "Mythical [EVENT]", icon: "⚪", order: 72 },
  mythical_limited: { name: "Mythical [LIMITED]", icon: "⚪", order: 73 },
  mythical_special: { name: "Mythical [SPECIAL]", icon: "⚪", order: 74 },
  cherished: { name: "Cherished", icon: "🌸", order: 80 },
  eternity: { name: "Eternity", icon: "🔴", order: 90 },
  dungeon_tier_1: { name: "Dungeon Tier 1", icon: "🔸", order: 100 },
  dungeon_tier_2: { name: "Dungeon Tier 2", icon: "🔶", order: 101 },
  dungeon_key: { name: "Dungeon Key", icon: "🗝️", order: 102 },
  unknown: { name: "Unknown", icon: "?", order: 999 }
};

const CURRENCY_META = {
  default: { name: "Default", icon: "$" },
  unknown: { name: "Default", icon: "$" },
  memory_petal: { name: "Memory Petal", icon: "https://raw.githubusercontent.com/PhantomSouLy/GaCherry-Assets/main/Icons/Currency/MemoryPetal.png" },
  legendary_shard: { name: "Legendary Shard", icon: "https://raw.githubusercontent.com/PhantomSouLy/GaCherry-Assets/main/Icons/Currency/LegendaryShard.png" },
  eternity_shard: { name: "Eternity Shard", icon: "https://raw.githubusercontent.com/PhantomSouLy/GaCherry-Assets/main/Icons/Currency/EternityShard.png" },
  definitely_not_mythical_shard: { name: "Definitely Not Mythical Shard", icon: "https://raw.githubusercontent.com/PhantomSouLy/GaCherry-Assets/main/Icons/Currency/DefinitelyNotMythicalShard.png" },
  mythical_shard: { name: "Mythical Shard", icon: "https://raw.githubusercontent.com/PhantomSouLy/GaCherry-Assets/main/Icons/Currency/MythicalShard.png" },
  gold_bar: { name: "Gold Bar", icon: "https://raw.githubusercontent.com/PhantomSouLy/GaCherry-Assets/main/Icons/Currency/GoldBar.png" },
  dungeon_key: { name: "Dungeon Key", icon: "https://raw.githubusercontent.com/PhantomSouLy/GaCherry-Assets/main/Icons/Currency/DungeonKey.png" },
  echo_bloom: { name: "Echo Bloom", icon: "https://raw.githubusercontent.com/PhantomSouLy/GaCherry-Assets/main/Icons/Currency/EchoBloom.png" }
};

const state = { database:null, cards:[], filtered:[], activePage:"collection", activeTag:"All", activeRarity:"All", activeSource:"All", sort:"id-asc", search:"", currentPage:1, perPage:60, compact:false };
const els = {};
function $(id){ return document.getElementById(id); }
function setupElements(){ ["sideTotal","sideRarityCount","sideSourceCount","resultCount","totalCardsNumber","totalProgressBar","rarityPanelTotal","rarityStatsGrid","searchInput","clearSearchBtn","raritySelect","sourceSelect","sortSelect","quickFilters","tagFilters","cardGallery","prevPage","nextPage","pageNumbers","perPageSelect","emptyState","rarityOverview","sourceOverview","gridViewBtn","compactViewBtn","cardModal","closeModal","modalImage","modalPlaceholder","modalId","modalRarity","modalSource","modalTitle","modalDescription","modalCategory","modalSeries","modalEvent","modalType","modalSell","modalBuy","modalStock","modalMaxUser","modalRole","modalTags"].forEach(id=>els[id]=$(id)); }
function normalizeKey(value){ return String(value||"").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\+/g," plus ").replace(/\[(.*?)\]/g," $1 ").replace(/[^a-z0-9]+/g,"_").replace(/^_+|_+$/g,""); }
function normalizeRarityId(value){ const id=normalizeKey(value||"unknown"); if(RARITY_META[id]) return id; const found=Object.entries(RARITY_META).find(([,m])=>m.name.toLowerCase()===String(value||"").toLowerCase()); return found?found[0]:(id||"unknown"); }
function getRarityMeta(cardOrRarity){ const id=typeof cardOrRarity==='object'?normalizeRarityId(cardOrRarity.rarity||cardOrRarity.rarityName):normalizeRarityId(cardOrRarity); const meta=RARITY_META[id]||{}; return { id, name: typeof cardOrRarity==='object'?(cardOrRarity.rarityName||meta.name||id):(meta.name||String(cardOrRarity||"Unknown")), icon: typeof cardOrRarity==='object'?(cardOrRarity.rarityIcon||meta.icon||""):(meta.icon||"")}; }
function normalizeCurrencyId(value){ const id=normalizeKey(value||"default"); if(id==="unknown") return "default"; if(CURRENCY_META[id]) return id; const found=Object.entries(CURRENCY_META).find(([,m])=>m.name.toLowerCase()===String(value||"").toLowerCase()); return found?found[0]:(id||"default"); }
function getCurrencyMeta(card){ const id=normalizeCurrencyId(card.currency||card.currencyName||"default"); const meta=CURRENCY_META[id]||CURRENCY_META.default; return { id, name: card.currencyName&&card.currencyName!=="Unknown"?card.currencyName:meta.name, icon: card.currencyIcon&&card.currencyIcon!=="❔"&&card.currencyIcon!=="?"?card.currencyIcon:meta.icon, confidence: card.currencyConfidence||"unknown" }; }
function rarityClass(rarity){ const id=normalizeRarityId(rarity); if(id.includes("common")) return id.includes("uncommon")?"uncommon":"common"; if(id.includes("rare")) return "rare"; if(id.includes("epic")) return "epic"; if(id.includes("legendary")) return "legendary"; if(id.includes("relic")) return "relic"; if(id.includes("mythical")) return "mythical"; if(id.includes("cherished")) return "cherished"; if(id.includes("eternity")) return "eternity"; return "unknown"; }
function safeText(value,fallback="-"){ return value===null||value===undefined||value===""?fallback:String(value); }
function getAssetBase(){ return state.database?.assetBaseUrl || "https://raw.githubusercontent.com/PhantomSouLy/GaCherry-Assets/main/"; }
function getImageUrl(card){ const url = card.image || card.asset || ""; if(!url) return ""; if(/^https?:\/\//i.test(url)) return encodeURI(url); return encodeURI(getAssetBase()+url); }
function getRarityLabel(r){ const id=normalizeRarityId(r); return RARITY_META[id]?.name || String(r||"Unknown"); }
function getRarityIcon(r){ const id=normalizeRarityId(r); return RARITY_META[id]?.icon || "✦"; }
function getRarityOrder(){ const stats=state.database?.statistics?.rarity||{}; return Object.keys(stats).sort((a,b)=>(RARITY_META[a]?.order??999)-(RARITY_META[b]?.order??999)||getRarityLabel(a).localeCompare(getRarityLabel(b),"hu")); }
function getRarityRank(r){ const idx=getRarityOrder().indexOf(normalizeRarityId(r)); return idx===-1?9999:idx; }
function normalizeSource(value){ const upper=String(value||"Unknown").trim().toUpperCase().replace(/\s+/g,""); return {NODROP:"NoDrop",STORE:"Store",GACHA:"Gacha",DUNGEON:"Dungeon",CURRENCY:"Currency",BUNDLE:"Bundle",MERGE:"Merge"}[upper] || String(value||"Unknown").trim(); }
function normalizeTag(tag){ const text=String(tag||"").trim(); const upper=text.toUpperCase().replace(/\s+/g,""); if(!text||upper==="PREMIUM") return ""; if(upper==="NODROP") return "NoDrop"; if(upper==="UNTRADABLE") return "Untradable"; if(upper==="LIMITED") return "Limited"; if(upper==="EVENT") return "Event"; if(upper==="BUNDLE"||upper==="BUNDLES") return "Bundle"; if(upper==="DEDICATED") return "Dedicated"; return text; }
function uniqueTags(tags){ return [...new Set((Array.isArray(tags)?tags:[]).map(normalizeTag).filter(Boolean))]; }
function normalizeMergeKey(card){ return [normalizeRarityId(card.rarity||card.rarityName), card.name||""].join("|").toLowerCase(); }
function mergeCardLists(groups){ const merged=[]; const map=new Map(); groups.forEach(group=>(group||[]).forEach(card=>{ const key=normalizeMergeKey(card); if(map.has(key)){ const i=map.get(key), old=merged[i]; merged[i]={...old,...card,id:old.id??card.id,slug:card.slug||old.slug,category:card.category||old.category,series:card.series??old.series??null,event:card.event??old.event??null,tags:uniqueTags([...(old.tags||[]),...(card.tags||[])])}; } else { map.set(key,merged.length); merged.push(card); }})); return merged; }
function normalizeCard(card,index){ const source=normalizeSource(card.type||card.source||"Unknown"); const rarity=getRarityMeta(card); const currency=getCurrencyMeta(card); return {_uid:index+1,_sortId:index+1,id:card.id??index+1,slug:card.slug||"",name:card.name||`Card ${index+1}`,rarity:rarity.id,rarityName:rarity.name,rarityIcon:rarity.icon,source,type:source,category:card.category||"Uncategorized",series:card.series??null,event:card.event??null,tags:uniqueTags(card.tags),asset:card.asset||"",image:card.image||"",imageOriginal:card.imageOriginal||"",description:card.description||"",currency:currency.id,currencyName:currency.name,currencyIcon:currency.icon,currencyConfidence:currency.confidence,tradable:card.tradable??null,sell:card.sell??null,buy:card.buy??null,stock:card.stock??null,maxPerUser:card.maxPerUser??null,role:card.role??null,rawText:card.rawText||""}; }
async function fetchJsonOptional(url){ try{ const res=await fetch(url,{cache:"no-store"}); if(!res.ok) return null; return await res.json(); }catch(e){ console.warn("Nem sikerült betölteni:",url,e); return null; } }
async function getExtraCardFiles(){ const index=await fetchJsonOptional(CARD_DATA_INDEX_URL); const files=Array.isArray(index?.files)?index.files:FALLBACK_CARD_DATA_FILES; return files.filter(Boolean).map(f=>f.startsWith("./")||f.startsWith("/")||/^https?:\/\//i.test(f)?f:`./data/cards/${f}`); }
function calculateStatistics(cards){ return {rarity:countBy(cards,"rarity"),source:countBy(cards,"source"),raritySource:cards.reduce((a,c)=>{a[c.rarity]??={};a[c.rarity][c.source]=(a[c.rarity][c.source]||0)+1;return a;},{})}; }
async function loadDatabase(){ const core=await fetchJsonOptional(CORE_DATA_URL) || {cards:[]}; const extraFiles=await getExtraCardFiles(); const extras=(await Promise.all(extraFiles.map(fetchJsonOptional))).filter(Boolean); const rawCards=mergeCardLists([...extras.map(db=>db.cards||[]), core.cards||[]]); const normalized=rawCards.map(normalizeCard); state.database={...core,generatedAt:new Date().toISOString(),totalCards:normalized.length,loadedFiles:[...extraFiles,CORE_DATA_URL],statistics:calculateStatistics(normalized)}; state.cards=normalized; state.filtered=[...state.cards]; renderAll(); }
function renderAll(){ renderSidebarStats(); renderRarityDashboard(); renderControls(); renderRarityOverview(); renderSourceOverview(); applyFilters(); }
function renderSidebarStats(){ const rarityCount=Object.keys(state.database?.statistics?.rarity||{}).length; const sourceCount=Object.keys(state.database?.statistics?.source||{}).length; els.sideTotal.textContent=state.cards.length; els.sideRarityCount.textContent=rarityCount; els.sideSourceCount.textContent=sourceCount; els.totalCardsNumber.textContent=state.cards.length; els.rarityPanelTotal.textContent=`${state.cards.length} összesen`; }
function renderRarityDashboard(){ const stats=state.database?.statistics?.rarity||countBy(state.cards,"rarity"); const total=state.cards.length||1; els.rarityStatsGrid.innerHTML=getRarityOrder().map(r=>{const count=stats[r]||0,pct=Math.round((count/total)*1000)/10,cls=rarityClass(r);return `<button class="rarity-stat" data-rarity="${escapeAttr(r)}" title="${escapeAttr(getRarityLabel(r))}"><strong><span class="mini-icon ${cls}">${escapeHtml(getRarityIcon(r))}</span> ${escapeHtml(getRarityLabel(r))}</strong><span>${count} / ${total}</span><b class="rarity-badge ${cls}">${pct}%</b></button>`}).join(""); els.rarityStatsGrid.querySelectorAll("[data-rarity]").forEach(btn=>btn.addEventListener("click",()=>{state.activeRarity=btn.dataset.rarity;state.currentPage=1;syncControls();applyFilters();})); }
function renderControls(){ const rarities=["All",...getRarityOrder()]; const sources=["All",...Object.keys(state.database?.statistics?.source||countBy(state.cards,"source")).sort()]; const tags=getAllTags(); els.raritySelect.innerHTML=rarities.map(r=>`<option value="${escapeAttr(r)}">${r==="All"?"Rarity (Összes)":escapeHtml(getRarityLabel(r))}</option>`).join(""); els.sourceSelect.innerHTML=sources.map(s=>`<option value="${escapeAttr(s)}">${s==="All"?"Source (Összes)":escapeHtml(s)}</option>`).join(""); els.quickFilters.innerHTML=rarities.map(r=>`<button class="filter-chip ${r==="All"?"active":""}" data-rarity="${escapeAttr(r)}">${r==="All"?"Összes":`${escapeHtml(getRarityIcon(r))} ${escapeHtml(getRarityLabel(r))}`}</button>`).join("")+sources.filter(s=>s!=="All").map(s=>`<button class="filter-chip source-chip" data-source="${escapeAttr(s)}">${escapeHtml(s)}</button>`).join(""); els.tagFilters.innerHTML=[`<button class="tag-chip active" data-tag="All">Minden tag</button>`].concat(tags.map(tag=>`<button class="tag-chip" data-tag="${escapeAttr(tag)}">${escapeHtml(tag)}</button>`)).join(""); els.quickFilters.onclick=e=>{const btn=e.target.closest("button"); if(!btn)return; if(btn.dataset.rarity)state.activeRarity=btn.dataset.rarity; if(btn.dataset.source)state.activeSource=state.activeSource===btn.dataset.source?"All":btn.dataset.source; state.currentPage=1; syncControls(); applyFilters();}; els.tagFilters.onclick=e=>{const btn=e.target.closest("button"); if(!btn)return; state.activeTag=btn.dataset.tag; state.currentPage=1; syncControls(); applyFilters();}; }
function syncControls(){ els.raritySelect.value=state.activeRarity; els.sourceSelect.value=state.activeSource; els.quickFilters.querySelectorAll("[data-rarity]").forEach(btn=>btn.classList.toggle("active",btn.dataset.rarity===state.activeRarity)); els.quickFilters.querySelectorAll("[data-source]").forEach(btn=>btn.classList.toggle("active",btn.dataset.source===state.activeSource)); els.tagFilters.querySelectorAll("[data-tag]").forEach(btn=>btn.classList.toggle("active",btn.dataset.tag===state.activeTag)); }
function renderRarityOverview(){ const stats=state.database?.statistics?.rarity||countBy(state.cards,"rarity"); els.rarityOverview.innerHTML=getRarityOrder().map(r=>`<article class="overview-card"><h3><span class="rarity-badge ${rarityClass(r)}">${escapeHtml(getRarityIcon(r))} ${escapeHtml(getRarityLabel(r))}</span></h3><div class="overview-number">${stats[r]||0}</div><small>kártya ebben a rarityben</small></article>`).join(""); }
function renderSourceOverview(){ const stats=state.database?.statistics?.source||countBy(state.cards,"source"); els.sourceOverview.innerHTML=Object.entries(stats).sort((a,b)=>b[1]-a[1]).map(([s,c])=>`<article class="overview-card"><h3><span class="source-badge">${escapeHtml(s)}</span></h3><div class="overview-number">${c}</div><small>kártya ebben a source-ban</small></article>`).join(""); }
function getAllTags(){ const tags=new Set(); state.cards.forEach(c=>c.tags.forEach(t=>tags.add(t))); return [...tags].sort((a,b)=>a.localeCompare(b,"hu")); }
function countBy(list,key){ return list.reduce((a,item)=>{const v=item[key]||"unknown"; a[v]=(a[v]||0)+1; return a;},{}); }
function applyFilters(){ const search=state.search.trim().toLowerCase(); let result=state.cards.filter(c=>{ const matchesRarity=state.activeRarity==="All"||c.rarity===state.activeRarity; const matchesSource=state.activeSource==="All"||c.source===state.activeSource; const matchesTag=state.activeTag==="All"||c.tags.includes(state.activeTag); const haystack=[c.name,c.rarity,c.rarityName,c.source,c.type,c.currency,c.currencyName,c.category,c.series,c.event,c.description,...c.tags].filter(Boolean).join(" ").toLowerCase(); return matchesRarity&&matchesSource&&matchesTag&&(!search||haystack.includes(search)); }); result.sort(sortCards); state.filtered=result; clampPage(); renderCards(); renderPagination(); }
function sortCards(a,b){ switch(state.sort){ case "id-desc":return b._sortId-a._sortId; case "name-asc":return a.name.localeCompare(b.name,"hu"); case "name-desc":return b.name.localeCompare(a.name,"hu"); case "rarity-desc":return getRarityRank(b.rarity)-getRarityRank(a.rarity)||a.name.localeCompare(b.name,"hu"); case "rarity-asc":return getRarityRank(a.rarity)-getRarityRank(b.rarity)||a.name.localeCompare(b.name,"hu"); default:return a._sortId-b._sortId; } }
function clampPage(){ const max=Math.max(1,Math.ceil(state.filtered.length/state.perPage)); state.currentPage=Math.min(Math.max(1,state.currentPage),max); }
function renderCards(){ const visible=state.filtered.slice((state.currentPage-1)*state.perPage,(state.currentPage-1)*state.perPage+state.perPage); els.resultCount.textContent=`${state.filtered.length} kártya`; els.emptyState.style.display=visible.length?"none":"block"; els.cardGallery.classList.toggle("compact",state.compact); els.cardGallery.innerHTML=visible.map(createCardHTML).join(""); els.cardGallery.querySelectorAll(".card").forEach(el=>el.addEventListener("click",()=>openModal(state.cards.find(c=>c._uid===Number(el.dataset.uid))))); els.cardGallery.querySelectorAll("img[data-src]").forEach(img=>{ img.addEventListener("load",()=>{img.classList.add("loaded"); img.closest(".image-shell")?.classList.add("image-loaded");},{once:true}); img.addEventListener("error",()=>{img.alt="A kép nem tölthető be"; img.classList.add("loaded");},{once:true}); img.src=img.dataset.src; }); }
function formatCardId(card){ return `#${String(card._uid).padStart(3,"0")}`; }
function formatValue(value,fallback="-"){ return value===null||value===undefined||value===""?fallback:String(value); }
function formatCurrencyValue(value,card){ if(value===null||value===undefined||value==="")return "-"; const icon=card.currencyIcon||"$"; const name=card.currencyName||"Default"; const val=`<b>${escapeHtml(value)}</b>`; if(/^https?:\/\//i.test(icon))return `<span class="currency-value" title="${escapeAttr(name)}"><img class="currency-icon" src="${escapeAttr(icon)}" alt="${escapeAttr(name)}"> ${val}</span>`; return `<span class="currency-value" title="${escapeAttr(name)}"><span class="currency-emoji">${escapeHtml(icon)}</span> ${val}</span>`; }
function createCardHTML(card){ const cls=rarityClass(card.rarity), imageUrl=getImageUrl(card); const rarityLabel=`${card.rarityIcon?`${card.rarityIcon} `:""}${card.rarityName||getRarityLabel(card.rarity)}`; return `<article class="card ${cls}" data-uid="${card._uid}"><div class="image-shell"><div class="placeholder">${escapeHtml(card.rarityName||getRarityLabel(card.rarity))}</div><img data-src="${escapeAttr(imageUrl)}" alt="${escapeAttr(card.name)}" loading="lazy"></div><div class="card-info"><div class="card-name">${escapeHtml(card.name)}</div><div class="card-meta"><span class="rarity-badge ${cls}">${escapeHtml(rarityLabel)}</span><span class="card-id">${formatCardId(card)}</span></div></div></article>`; }
function renderPagination(){ const total=Math.max(1,Math.ceil(state.filtered.length/state.perPage)); els.prevPage.disabled=state.currentPage<=1; els.nextPage.disabled=state.currentPage>=total; els.pageNumbers.innerHTML=buildPageList(state.currentPage,total).map(p=>p==="..."?`<span class="dots">...</span>`:`<button class="${p===state.currentPage?"active":""}" data-page="${p}">${p}</button>`).join(""); els.pageNumbers.querySelectorAll("[data-page]").forEach(btn=>btn.addEventListener("click",()=>{state.currentPage=Number(btn.dataset.page);renderCards();renderPagination();window.scrollTo({top:0,behavior:"smooth"});})); }
function buildPageList(current,total){ if(total<=7)return Array.from({length:total},(_,i)=>i+1); const pages=[1]; if(current>4)pages.push("..."); for(let i=Math.max(2,current-1);i<=Math.min(total-1,current+1);i++)pages.push(i); if(current<total-3)pages.push("..."); pages.push(total); return pages; }
function openModal(card){ if(!card)return; const cls=rarityClass(card.rarity), imageUrl=getImageUrl(card); const rarityLabel=`${card.rarityIcon?`${card.rarityIcon} `:""}${card.rarityName||getRarityLabel(card.rarity)}`; els.cardModal.classList.add("open"); els.cardModal.setAttribute("aria-hidden","false"); els.modalImage.classList.remove("loaded"); els.modalImage.src=""; els.modalImage.alt=card.name; els.modalPlaceholder.className=`modal-placeholder ${cls}`; els.modalImage.onload=()=>{els.modalImage.classList.add("loaded"); els.modalImage.parentElement?.classList.add("image-loaded");}; els.modalImage.src=imageUrl; els.modalId.textContent=formatCardId(card); els.modalRarity.className=`rarity-badge ${cls}`; els.modalRarity.textContent=rarityLabel; els.modalSource.textContent=card.source; els.modalTitle.textContent=card.name; els.modalDescription.textContent=card.description||"Nincs külön leírás megadva."; els.modalCategory.textContent=safeText(card.category); els.modalSeries.textContent=safeText(card.series); els.modalEvent.textContent=safeText(card.event); if(els.modalType)els.modalType.textContent=safeText(card.type||card.source); if(els.modalSell)els.modalSell.innerHTML=formatCurrencyValue(card.sell,card); if(els.modalBuy)els.modalBuy.innerHTML=formatCurrencyValue(card.buy,card); if(els.modalStock)els.modalStock.textContent=formatValue(card.stock); if(els.modalMaxUser)els.modalMaxUser.textContent=formatValue(card.maxPerUser); if(els.modalRole)els.modalRole.textContent=formatValue(card.role); els.modalTags.innerHTML=card.tags.length?card.tags.map(t=>`<span>${escapeHtml(t)}</span>`).join(""):`<span>Nincs tag</span>`; }
function closeModal(){ els.cardModal.classList.remove("open"); els.cardModal.setAttribute("aria-hidden","true"); }
function showPage(pageId){ state.activePage=pageId; document.querySelectorAll(".page").forEach(p=>p.classList.remove("active")); document.getElementById(pageId)?.classList.add("active"); document.querySelectorAll("[data-page]").forEach(btn=>btn.classList.toggle("active",btn.dataset.page===pageId)); window.scrollTo({top:0,behavior:"smooth"}); }
function escapeHtml(value){ return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;"); }
function escapeAttr(value){ return escapeHtml(value).replaceAll("`","&#096;"); }
function bindEvents(){ document.querySelectorAll("[data-page]").forEach(btn=>btn.addEventListener("click",()=>showPage(btn.dataset.page))); els.searchInput.addEventListener("input",()=>{state.search=els.searchInput.value;state.currentPage=1;applyFilters();}); els.clearSearchBtn.addEventListener("click",()=>{els.searchInput.value="";state.search="";state.currentPage=1;applyFilters();}); els.raritySelect.addEventListener("change",()=>{state.activeRarity=els.raritySelect.value;state.currentPage=1;syncControls();applyFilters();}); els.sourceSelect.addEventListener("change",()=>{state.activeSource=els.sourceSelect.value;state.currentPage=1;syncControls();applyFilters();}); els.sortSelect.addEventListener("change",()=>{state.sort=els.sortSelect.value;applyFilters();}); els.perPageSelect.addEventListener("change",()=>{state.perPage=Number(els.perPageSelect.value);state.currentPage=1;applyFilters();}); els.prevPage.addEventListener("click",()=>{state.currentPage-=1;clampPage();renderCards();renderPagination();window.scrollTo({top:0,behavior:"smooth"});}); els.nextPage.addEventListener("click",()=>{state.currentPage+=1;clampPage();renderCards();renderPagination();window.scrollTo({top:0,behavior:"smooth"});}); els.gridViewBtn.addEventListener("click",()=>{state.compact=false;els.gridViewBtn.classList.add("active");els.compactViewBtn.classList.remove("active");renderCards();}); els.compactViewBtn.addEventListener("click",()=>{state.compact=true;els.compactViewBtn.classList.add("active");els.gridViewBtn.classList.remove("active");renderCards();}); els.closeModal.addEventListener("click",closeModal); els.cardModal.addEventListener("click",e=>{if(e.target.classList.contains("modal-backdrop"))closeModal();}); document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal();}); }
async function init(){ setupElements(); bindEvents(); try{ await loadDatabase(); }catch(e){ console.error(e); els.resultCount.textContent="Nem sikerült betölteni az adatbázist."; els.cardGallery.innerHTML=`<article class="guide-card"><h3>Hiba</h3><p>${escapeHtml(e.message)}</p></article>`; } }
init();
