const DATA_INDEX='./data/cards/index.json', CURRENCIES_URL='./data/currencies/currencies.json', RARITIES_URL='./data/rarities/rarities.json', CRAFT_URL='./data/crafts/badge-craft.json', REDEEM_URL='./data/redeem/codes.json';
const state={cards:[],rarities:[],currencies:[],craft:null,redeem:null,guide:'intro',filters:{rarity:'all',type:'all',series:'all',tag:'all'},search:'',sort:'number-asc',currentPage:1,perPage:60};
const BASE=['common','uncommon','rare','epic','legendary','relic','mythical','cherished','eternity','dungeon_tier_1','dungeon_tier_2','dungeon_key','unknown'];
const LABEL={common:['🟢','Common'],uncommon:['⚫','Uncommon'],rare:['🔵','Rare'],epic:['🟣','Epic'],legendary:['🟠','Legendary'],relic:['🟡','Relic'],mythical:['⚪','Mythical'],cherished:['🌸','Cherished'],eternity:['🔴','Eternity'],dungeon_tier_1:['🔸','Dungeon Tier 1'],dungeon_tier_2:['🔶','Dungeon Tier 2'],dungeon_key:['🗝️','Dungeon Key'],unknown:['?','Unknown']};
const TYPES=['Gacha','Dungeon','Store','NoDrop','Craft','Bundle','Badge'], SERIES=['Legacy','New ERA'], TAGS=['Event','Limited','Special','Dedicated','Craft','Badge','Seasonal','Bundle','Untradable'];
const $=id=>document.getElementById(id), esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
async function getJson(u){const r=await fetch(u,{cache:'no-store'}); if(!r.ok) throw new Error('Nem sikerült betölteni: '+u); return r.json();}
async function load(){const idx=await getJson(DATA_INDEX); const dbs=await Promise.all((idx.files||[]).map(f=>getJson('./data/cards/'+f))); state.cards=dbs.flatMap(x=>x.cards||[]); state.rarities=(await getJson(RARITIES_URL)).rarities||[]; state.currencies=(await getJson(CURRENCIES_URL)).currencies||[]; state.craft=await getJson(CRAFT_URL); state.redeem=await getJson(REDEEM_URL); initTheme(); bind(); renderAll();}
function initTheme(){document.body.dataset.theme=localStorage.getItem('gacherry-theme')||'dark'; themeText();} function themeText(){const t=document.body.dataset.theme==='dark'?'🌙 Dark':'☀️ Light'; $('themeToggle').textContent=t; $('themeToggleTop').textContent=t;} function toggleTheme(){document.body.dataset.theme=document.body.dataset.theme==='dark'?'light':'dark'; localStorage.setItem('gacherry-theme',document.body.dataset.theme); themeText();}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page))); document.querySelectorAll('[data-guide]').forEach(b=>b.addEventListener('click',()=>{showPage('guide'); state.guide=b.dataset.guide; renderGuide();})); $('themeToggle').onclick=toggleTheme; $('themeToggleTop').onclick=toggleTheme; $('searchInput').oninput=e=>{state.search=e.target.value;state.currentPage=1;renderCards();}; $('clearSearch').onclick=()=>{state.search='';$('searchInput').value='';state.currentPage=1;renderCards();}; $('sortSelect').onchange=e=>{state.sort=e.target.value;renderCards();}; $('prevPage').onclick=()=>{state.currentPage--;renderCards();}; $('nextPage').onclick=()=>{state.currentPage++;renderCards();}; $('closeModal').onclick=closeModal; $('cardModal').onclick=e=>{if(e.target.classList.contains('modal-backdrop'))closeModal();}; document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();});}
function showPage(p){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active')); $(p+'Page')?.classList.add('active'); document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.page===p)); if(p==='guide')renderGuide(); scrollTo({top:0,behavior:'smooth'});}
function renderAll(){$('sideTotal').textContent=state.cards.length; $('homeCardCount').textContent=state.cards.length; $('homeRarityCount').textContent=new Set(state.cards.map(c=>c.rarityGroup)).size; $('homeCurrencyCount').textContent=state.currencies.length; renderRarityStats(); renderFilters(); renderCards(); renderRarities(); renderCurrencies(); renderCraft(); renderGuide(); renderRedeem();}
function countBy(arr,fn){const m={};arr.forEach(x=>{const k=fn(x);m[k]=(m[k]||0)+1});return m} function rarityLabel(g){return LABEL[g]||['?',g||'Unknown'];}
function renderRarityStats(){const c=countBy(state.cards,x=>x.rarityGroup||'unknown'); $('rarityStats').innerHTML=BASE.filter(g=>c[g]).map(g=>{const [i,l]=rarityLabel(g);return `<button class="rarity-tile ${state.filters.rarity===g?'active':''}" data-rarity="${esc(g)}"><span class="icon">${i}</span><strong>${esc(l)}</strong><span>${c[g]} db</span></button>`}).join(''); $('rarityStats').querySelectorAll('[data-rarity]').forEach(b=>b.onclick=()=>{state.filters.rarity=b.dataset.rarity;state.currentPage=1;showPage('cards');syncFilters();renderCards();});}
function chip(f,v,l){return `<button class="chip ${state.filters[f]===v?'active':''}" data-filter="${f}" data-value="${esc(v)}">${esc(l)}</button>`}
function renderFilters(){$('rarityFilters').innerHTML=chip('rarity','all','Összes')+BASE.filter(g=>state.cards.some(c=>c.rarityGroup===g)).map(g=>{const [i,l]=rarityLabel(g);return chip('rarity',g,`${i} ${l}`)}).join(''); $('typeFilters').innerHTML=chip('type','all','Összes')+TYPES.map(t=>chip('type',t,t)).join(''); $('seriesFilters').innerHTML=chip('series','all','Összes')+SERIES.map(s=>chip('series',s,s)).join(''); $('tagFilters').innerHTML=chip('tag','all','Minden tag')+TAGS.map(t=>chip('tag',t,t)).join(''); document.querySelectorAll('.chip[data-filter]').forEach(b=>b.onclick=()=>{state.filters[b.dataset.filter]=b.dataset.value;state.currentPage=1;syncFilters();renderCards();});}
function syncFilters(){document.querySelectorAll('.chip[data-filter]').forEach(b=>b.classList.toggle('active',state.filters[b.dataset.filter]===b.dataset.value)); renderRarityStats();}
function match(c){if(state.filters.rarity!=='all'&&c.rarityGroup!==state.filters.rarity)return false; if(state.filters.type!=='all'){let t=state.filters.type;if(['Craft','Bundle','Badge'].includes(t)){if(!(c.tags||[]).includes(t))return false;}else if(!(c.types||[]).includes(t))return false;} if(state.filters.series!=='all'&&c.series!==state.filters.series)return false; if(state.filters.tag!=='all'&&!(c.tags||[]).includes(state.filters.tag))return false; const q=state.search.trim().toLowerCase(); if(q){const h=[c.name,c.description,c.rarityName,c.rarityGroup,c.type,c.series,c.currencyName,...(c.tags||[]),...(c.types||[])].join(' ').toLowerCase(); if(!h.includes(q))return false;} return true;}
function sorter(a,b){if(state.sort==='number-desc')return(b.number||0)-(a.number||0); if(state.sort==='name-asc')return a.name.localeCompare(b.name,'hu'); if(state.sort==='name-desc')return b.name.localeCompare(a.name,'hu'); if(state.sort==='rarity-asc')return BASE.indexOf(a.rarityGroup)-BASE.indexOf(b.rarityGroup)||a.name.localeCompare(b.name,'hu'); return(a.number||0)-(b.number||0)}
function renderCards(){let list=state.cards.filter(match).sort(sorter), pages=Math.max(1,Math.ceil(list.length/state.perPage)); state.currentPage=Math.min(Math.max(1,state.currentPage),pages); let page=list.slice((state.currentPage-1)*state.perPage,state.currentPage*state.perPage); $('resultCount').textContent=list.length+' kártya'; $('cardsGrid').innerHTML=page.map(c=>`<article class="card" data-number="${c.number}"><div class="image-shell"><img src="${esc(c.image)}" alt="${esc(c.name)}" loading="lazy"></div><div class="card-info"><div class="card-name">${esc(c.name)}</div><div class="card-meta"><span class="rarity-badge">${esc(c.rarityIcon)} ${esc(c.rarityName)}</span><span class="card-id">#${String(c.number).padStart(3,'0')}</span></div></div></article>`).join(''); $('cardsGrid').querySelectorAll('.card').forEach(el=>el.onclick=()=>openModal(state.cards.find(c=>String(c.number)===el.dataset.number))); $('prevPage').disabled=state.currentPage<=1; $('nextPage').disabled=state.currentPage>=pages; $('pageNumbers').innerHTML=`<button class="active">${state.currentPage}</button>`;}
function curVal(v,c){if(v===null||v===undefined||v==='')return '-';const cur=state.currencies.find(x=>x.id===c.currency)||{icon:'$',name:'Default'};return String(cur.icon||'$').startsWith('data/')?`<span class="currency-value"><img src="${esc(cur.icon)}" alt="${esc(cur.name)}"><b>${esc(v)}</b></span>`:`<span class="currency-value"><span>${esc(cur.icon||'$')}</span><b>${esc(v)}</b></span>`}
function openModal(c){$('cardModal').classList.add('open'); $('modalImage').src=c.image; $('modalNumber').textContent='#'+String(c.number).padStart(3,'0'); $('modalRarity').textContent=`${c.rarityIcon} ${c.rarityName}`; $('modalTypes').textContent=(c.types||[]).join(', '); $('modalTitle').textContent=c.name; $('modalDescription').textContent=c.description||'Nincs külön leírás megadva.'; $('modalSeries').textContent=c.series||'-'; $('modalTypeList').textContent=(c.types||[]).join(', ')||'-'; $('modalSell').innerHTML=curVal(c.sell,c); $('modalBuy').innerHTML=curVal(c.buy,c); $('modalStock').textContent=c.stock??'-'; $('modalMaxUser').textContent=c.maxPerUser??'-'; $('modalRole').textContent=c.role||'-'; $('modalRoleRow').style.display=c.role?'flex':'none'; const tags=c.tags||[]; $('modalTags').innerHTML=tags.length?tags.map(t=>`<span>${esc(t)}</span>`).join(''):'<span>Nincs tag</span>';}
function closeModal(){$('cardModal').classList.remove('open')}
function renderRarities(){const c=countBy(state.cards,x=>x.rarityGroup); $('rarityList').innerHTML=BASE.filter(g=>c[g]).map(g=>{const [i,l]=rarityLabel(g);return `<button class="rarity-tile" data-rarity-page="${g}"><span class="icon">${i}</span><strong>${esc(l)}</strong><span>${c[g]} db</span></button>`}).join(''); $('rarityList').querySelectorAll('[data-rarity-page]').forEach(b=>b.onclick=()=>{state.filters.rarity=b.dataset.rarityPage;state.currentPage=1;showPage('cards');syncFilters();renderCards();});}
function renderCurrencies(){$('currencyList').innerHTML=state.currencies.map(c=>`<article class="currency-tile">${String(c.icon).startsWith('data/')?`<img src="${esc(c.icon)}" alt="${esc(c.name)}">`:`<span class="currency-symbol">${esc(c.icon||'$')}</span>`}<strong>${esc(c.name)}</strong></article>`).join('')}
function linkable(t){let q=String(t).replace(/^\d+×?\s*/,'').replace(/\s*\((Store|Gacha|Dungeon)\)/i,'').replace(/\s*\[\d+x\]/i,'').trim();return `<span class="craft-chip" data-craft-search="${esc(q)}">${esc(t)}</span>`}
function renderCraft(){let levels=state.craft?.levels||[]; $('craftTree').innerHTML=levels.map(l=>`<article class="craft-card"><h3>${esc(l.title)}</h3><p><b>Eredmény:</b> ${linkable(l.result)}</p><p><b>Rarity:</b> ${esc(l.rarity)} · <b>Role:</b> ${esc(l.role)}</p><h4>Szükséges:</h4><ul>${l.requirements.map(x=>`<li>${linkable(x)}</li>`).join('')}</ul>${l.subcrafts.map(s=>`<h4>${esc(s.title)}</h4><ul>${s.items.map(x=>`<li>${linkable(x)}</li>`).join('')}</ul>`).join('')}</article>`).join(''); document.querySelectorAll('[data-craft-search]').forEach(e=>e.onclick=()=>{state.search=e.dataset.craftSearch;$('searchInput').value=state.search;showPage('cards');renderCards();});}
const GUIDE={intro:['Bevezetés','<p>A GaCherry egy Discord gacha játék HappyCherryChan közösségéhez. Ez az oldal a <b>GaCherry Database</b>: kártyák, rarityk, guide-ok, craftok és kódok egy helyen.</p>'],commands:['Parancsok','<ul><li><code>/gacha</code> – Kártyanyitás.</li><li><code>/store</code> – Bolt.</li><li><code>/dungeon</code> – Dungeon.</li><li><code>/daily</code> – Napi jutalom.</li><li><code>/work</code> – Munka.</li><li><code>/inventory</code> – Kártyák.</li><li><code>/wallet</code> – Pénznemek.</li><li><code>/profile</code> – Profil.</li><li><code>/redeem</code> – Kuponkód.</li><li><code>/merge</code> – Craft.</li></ul>'],profile:['Profil','<p>Profilt készíthetsz magadnak, saját kiírással, profilképpel és kártyakollekcióval.</p>'],gacha:['Gacha','<p><code>/gacha</code> paranccsal tudsz kártyát nyitni. Ingyen nyitás időzítő alapján, fizetős nyitás külön ablakból.</p>'],shop:['Bolt','<p><code>/store</code> alatt vásárolhatsz kártyákat, bundle-öket és craft itemeket.</p>'],dungeon:['Dungeon','<p><code>/dungeon</code> egy minigame. Dungeon Key kell hozzá, és Gold Bar is szerezhető belőle.</p>'],money:['Pénznemek','<ul><li>Default: alap pénznem.</li><li>Legendary Shard: Legendary kör.</li><li>Gold Bar: Relic/Dungeon kör.</li><li>Dungeon Key: dungeon belépés.</li><li>Mythical Shard: Mythical kör.</li><li>Memory Petal: Cherished craft.</li><li>Eternity Shard: Eternity kör.</li></ul>'],coupons:['Kuponok','<p>Kuponkód beváltása: <code>/redeem</code>. Az aktív és lejárt kódok külön oldalon jelennek meg.</p>'],faq:['GYIK','<p><b>Ez menti a Discord állapotomat?</b><br>Nem. Ez egy nézegető és adatbázis oldal.</p>']};
function renderGuide(){$('guideTabs').innerHTML=Object.entries(GUIDE).map(([id,g])=>`<button class="${state.guide===id?'active':''}" data-guide-tab="${id}">${esc(g[0])}</button>`).join(''); $('guideTabs').querySelectorAll('[data-guide-tab]').forEach(b=>b.onclick=()=>{state.guide=b.dataset.guideTab;renderGuide();}); let g=GUIDE[state.guide]||GUIDE.intro; $('guideContent').innerHTML=`<h3>${esc(g[0])}</h3>${g[1]}`;}
function renderRedeem(){const a=state.redeem?.active||[], e=state.redeem?.expired||[]; const card=c=>`<div class="redeem-item"><div class="redeem-code">${esc(c.code)}</div><p><b>Jutalom:</b> ${esc(c.reward)}</p><p><b>Lejár:</b> ${esc(c.expires||'-')}</p><small>${esc(c.note||'Beváltás Discordon: /redeem')}</small></div>`; $('redeemGrid').innerHTML=`<article class="redeem-card"><h3>🟢 Aktív kódok</h3>${a.map(card).join('')||'<p>Nincs aktív kód.</p>'}</article><article class="redeem-card"><h3>🔴 Lejárt kódok</h3>${e.map(card).join('')||'<p>Nincs lejárt kód feltöltve.</p>'}</article>`;}
load().catch(err=>{console.error(err);document.body.innerHTML=`<main style="padding:30px;color:white"><h1>Hiba</h1><p>${esc(err.message)}</p></main>`});
